apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:

      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      serviceAccountName: jenkins-eks
      containers:
        - name: jenkins
          image: elbekdev/jenkins2
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-data
          securityContext:
            runAsUser: 0
          ports:
            - name: httpport
              containerPort: 8080
      volumes:
        - name: jenkins-data 
          persistentVolumeClaim:
            claimName: jenkins-pv
          
    
          
              