apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv
spec:
  storageClassName: "generic"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
serviceAccountName: 
metadata:
  name: generic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: us-east-1a
  iopsPerGB: "10" 
  fsType: ext4
